{{- if .Values.MultiVideoGridJob.enabled }}
apiVersion: flink.nautilus.dellemc.com/v1beta1
kind: "FlinkApplication"
metadata:
  name: "multi-video-grid-job"
  labels:
    app: videoprocessor
    component: MultiVideoGridJob
    release: {{ $.Release.Name }}
spec:
  flinkVersion: 1.7.2
  mavenCoordinate: {{ .Values.mavenCoordinate.group }}:{{ .Values.mavenCoordinate.artifact }}:{{ .Values.mavenCoordinate.version }}
  mainClass: io.pravega.example.videoprocessor.MultiVideoGridJob

  parallelism: {{ .Values.MultiVideoGridJob.parallelism }}

  state: started

  parameters:
    - name: enableOperatorChaining
      value: {{ .Values.MultiVideoGridJob.enableOperatorChaining | quote }}
    - name: scope
      value: {{ $.Release.Namespace | quote }}
    - name: input-stream
      value: {{ .Values.MultiVideoGridJob.input.stream | quote }}
    - name: input-minNumSegments
      value: {{ .Values.MultiVideoGridJob.input.minNumSegments | quote }}
    - name: output-stream
      value: {{ .Values.MultiVideoGridJob.output.stream | quote }}
    - name: output-minNumSegments
      value: {{ .Values.MultiVideoGridJob.output.minNumSegments | quote }}
    - name: imageWidth
      value: {{ .Values.MultiVideoGridJob.imageWidth | quote }}
    - name: framesPerSec
      value: {{ .Values.MultiVideoGridJob.framesPerSec | quote }}
    - name: chunkSizeBytes
      value: {{ .Values.MultiVideoGridJob.chunkSizeBytes | quote }}
    - name: startAtTail
      value: {{ .Values.MultiVideoGridJob.startAtTail | quote }}
    - name: maxOutOfOrdernessMs
      value: {{ .Values.MultiVideoGridJob.maxOutOfOrdernessMs | quote }}
{{- end }}
