{{- if .Values.VideoDataGeneratorJob.enabled }}
apiVersion: flink.nautilus.dellemc.com/v1beta1
kind: "FlinkApplication"
metadata:
  name: "video-data-generator-job"
  labels:
    app: videoprocessor
    component: VideoDataGeneratorJob
    release: {{ $.Release.Name }}
spec:
  flinkVersion: 1.7.2
  mavenCoordinate: {{ .Values.mavenCoordinate.group }}:{{ .Values.mavenCoordinate.artifact }}:{{ .Values.mavenCoordinate.version }}
  mainClass: io.pravega.example.videoprocessor.VideoDataGeneratorJob

  parallelism: {{ .Values.VideoDataGeneratorJob.parallelism }}

  state: started

  parameters:
    - name: enableOperatorChaining
      value: {{ .Values.VideoDataGeneratorJob.enableOperatorChaining | quote }}
    - name: scope
      value: {{ $.Release.Namespace | quote }}
    - name: output-stream
      value: {{ .Values.MultiVideoGridJob.input.stream | quote }}
    - name: output-minNumSegments
      value: {{ .Values.MultiVideoGridJob.input.minNumSegments | quote }}
    - name: numCameras
      value: {{ .Values.VideoDataGeneratorJob.numCameras | quote }}
    - name: imageWidth
      value: {{ .Values.VideoDataGeneratorJob.imageWidth | quote }}
    - name: framesPerSec
      value: {{ .Values.VideoDataGeneratorJob.framesPerSec | quote }}
    - name: chunkSizeBytes
      value: {{ .Values.VideoDataGeneratorJob.chunkSizeBytes | quote }}
{{- end }}
