VideoDataGeneratorJob:
  parallelism: 6
  enableOperatorChaining: "true"
  useCachedFrame: "true"
  numCameras: 150 #96
  imageWidth: 450
  chunkSizeBytes: 524288
  framesPerSec: 3.0
  taskManager:
    replicas: 3
    memory: 2G
    cpu: 2000m
    taskSlots: 2

MultiVideoGridJob:
  enabled: false
  input:
    stream: video3
    minNumSegments: 96

VideoReaderJob:
  enabled: false
